
package webClientTest;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SI_EitfApInfors_Out_SynService", targetNamespace = "urn:newhope.com/SSC/Financial/Outbound", wsdlLocation = "file:/D:/BaiduNetdiskDownload/SI_EitfApInfors_Out_SynService.wsdl")
public class SIEitfApInforsOutSynService
    extends Service
{

    private final static URL SIEITFAPINFORSOUTSYNSERVICE_WSDL_LOCATION;
    private final static WebServiceException SIEITFAPINFORSOUTSYNSERVICE_EXCEPTION;
    private final static QName SIEITFAPINFORSOUTSYNSERVICE_QNAME = new QName("urn:newhope.com/SSC/Financial/Outbound", "SI_EitfApInfors_Out_SynService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/BaiduNetdiskDownload/SI_EitfApInfors_Out_SynService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIEITFAPINFORSOUTSYNSERVICE_WSDL_LOCATION = url;
        SIEITFAPINFORSOUTSYNSERVICE_EXCEPTION = e;
    }

    public SIEitfApInforsOutSynService() {
        super(__getWsdlLocation(), SIEITFAPINFORSOUTSYNSERVICE_QNAME);
    }

    public SIEitfApInforsOutSynService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIEITFAPINFORSOUTSYNSERVICE_QNAME, features);
    }

    public SIEitfApInforsOutSynService(URL wsdlLocation) {
        super(wsdlLocation, SIEITFAPINFORSOUTSYNSERVICE_QNAME);
    }

    public SIEitfApInforsOutSynService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIEITFAPINFORSOUTSYNSERVICE_QNAME, features);
    }

    public SIEitfApInforsOutSynService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIEitfApInforsOutSynService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SIEitfApInforsOutSyn
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIEitfApInforsOutSyn getHTTPPort() {
        return super.getPort(new QName("urn:newhope.com/SSC/Financial/Outbound", "HTTP_Port"), SIEitfApInforsOutSyn.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIEitfApInforsOutSyn
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIEitfApInforsOutSyn getHTTPPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:newhope.com/SSC/Financial/Outbound", "HTTP_Port"), SIEitfApInforsOutSyn.class, features);
    }

    /**
     * 
     * @return
     *     returns SIEitfApInforsOutSyn
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIEitfApInforsOutSyn getHTTPSPort() {
        return super.getPort(new QName("urn:newhope.com/SSC/Financial/Outbound", "HTTPS_Port"), SIEitfApInforsOutSyn.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIEitfApInforsOutSyn
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIEitfApInforsOutSyn getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:newhope.com/SSC/Financial/Outbound", "HTTPS_Port"), SIEitfApInforsOutSyn.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIEITFAPINFORSOUTSYNSERVICE_EXCEPTION!= null) {
            throw SIEITFAPINFORSOUTSYNSERVICE_EXCEPTION;
        }
        return SIEITFAPINFORSOUTSYNSERVICE_WSDL_LOCATION;
    }

}
