
package webClientTest;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SI_EitfApInfors_Out_Syn", targetNamespace = "urn:newhope.com/SSC/Financial/Outbound")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SIEitfApInforsOutSyn {


    /**
     * 
     * @param mtEitfApInforsReq
     * @return
     *     returns webClientTest.DTEitfApInforsResp
     */
    @WebMethod(operationName = "SI_EitfApInfors_Out_Syn", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_EitfApInfors_Resp", targetNamespace = "urn:newhope.com/SSC/Financial/Outbound", partName = "MT_EitfApInfors_Resp")
    public DTEitfApInforsResp siEitfApInforsOutSyn(
        @WebParam(name = "MT_EitfApInfors_Req", targetNamespace = "urn:newhope.com/SSC/Financial/Outbound", partName = "MT_EitfApInfors_Req")
        DTEitfApInforsReq mtEitfApInforsReq);

}
