
package webClient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TellService", targetNamespace = "http://webService/", wsdlLocation = "http://127.0.0.1:8080/tell?wsdl")
public class TellService
    extends Service
{

    private final static URL TELLSERVICE_WSDL_LOCATION;
    private final static WebServiceException TELLSERVICE_EXCEPTION;
    private final static QName TELLSERVICE_QNAME = new QName("http://webService/", "TellService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8080/tell?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TELLSERVICE_WSDL_LOCATION = url;
        TELLSERVICE_EXCEPTION = e;
    }

    public TellService() {
        super(__getWsdlLocation(), TELLSERVICE_QNAME);
    }

    public TellService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TELLSERVICE_QNAME, features);
    }

    public TellService(URL wsdlLocation) {
        super(wsdlLocation, TELLSERVICE_QNAME);
    }

    public TellService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TELLSERVICE_QNAME, features);
    }

    public TellService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TellService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Tell
     */
    @WebEndpoint(name = "TellPort")
    public Tell getTellPort() {
        return super.getPort(new QName("http://webService/", "TellPort"), Tell.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Tell
     */
    @WebEndpoint(name = "TellPort")
    public Tell getTellPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webService/", "TellPort"), Tell.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TELLSERVICE_EXCEPTION!= null) {
            throw TELLSERVICE_EXCEPTION;
        }
        return TELLSERVICE_WSDL_LOCATION;
    }

}
