
package webClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Tell", targetNamespace = "http://webService/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Tell {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Hello")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Hello", targetNamespace = "http://webService/", className = "webClient.Hello")
    @ResponseWrapper(localName = "HelloResponse", targetNamespace = "http://webService/", className = "webClient.HelloResponse")
    @Action(input = "http://webService/Tell/HelloRequest", output = "http://webService/Tell/HelloResponse")
    public String hello(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     *
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Love")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Love", targetNamespace = "http://webService/", className = "webClient.Love")
    @ResponseWrapper(localName = "LoveResponse", targetNamespace = "http://webService/", className = "webClient.LoveResponse")
    @Action(input = "http://webService/Tell/LoveRequest", output = "http://webService/Tell/LoveResponse")
    public String love(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

}
